# Develop build and deploy

name: oooi-front-dev
on:
  push:
    brances:
      - development

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci

      - run: set -eu
      - run: mkdir $HOME/.ssh
      - run: echo "${{ secrets.DEV_PRIVATE_KEY }}" > "$HOME/.ssh/github_private_key"
      - run: chmod 600 "$HOME/.ssh/github_private_key"

      - run: echo "${{ secrets.DEV_ENV }}" > ./.env
      - run: npm install
      - run: npm run build:dev

      -run: ls -la

      - run: rsync -e "ssh -i $HOME/.ssh/github_private_key -o StrictHostKeyChecking=no" --archive --compress --delete ./dist github-user@206.189.12.4:/var/www/dev.oooi.app/front/
